Feature/docker flor
latam-03-at/ml-service pull request #6
Opened 2022-03-14 22:29 UTC by florpadilla

Hi Luis, please review this pipeline. I modified the Jenkinsfile including the "Continuous Integration" and the "Continuous deployment" and the ports in the dockerfile.

2022-03-14 22:33 UTC, luisdavidparra requested changes

2022-03-14 22:33 UTC, luisdavidparra commented on Jenkinsfile
> +        stage('Upload to docker hub'){
You should document all the stages

2022-03-14 22:33 UTC, luisdavidparra commented on Jenkinsfile
> +        //aqu termina Continuous Integration
This comments must be in english

2022-03-15 02:29 UTC, florpadilla commented on Jenkinsfile
> +        //aqu termina Continuous Integration
Thanks! Done

2022-03-15 03:14 UTC, luisdavidparra commented
Looks good Maria!

2022-03-15 03:14 UTC, merged